export default {
  body: document.querySelector('body'),
  parent: document.querySelector('.lightbox-card-modal'),
  phone: document.querySelector('p.phone-title'),
  infoButton: document.querySelector('.card-modal__insert'),
  description: document.querySelector('.goods-modal__discription-text'),
  contactInfo: document.querySelector('.goods-modal__button'),
  price: document.querySelector('.goods-modal__price'),
  bigImage: document.querySelector('.card-modal__image-big'),
  title: document.querySelector('.goods-modal__title'),
  close: document.querySelector('.card-modal__close-btn'),
  closeSVG: document.querySelector('.card-modal__icon-close'),
  tumbnails: document.querySelector('.card-modal_tumbnails-list'),
  overlay: document.querySelector('.lightbox-card-modal__overlay'),
};
