export default {
    burgerButton: document.querySelector('.js-menu-button'),
    closeButton: document.querySelector('.js-close-button'),   
    nav: document.querySelector('.js-nav'),
    header: document.querySelector('.js-header'),    
    headerMenu: document.querySelector('.js-header-menu'),
    navList: document.querySelector('.js-header-list'),
    regButton: document.querySelector('.js-registry-button'),
    profileIcon: document.querySelector('.js-search-container__icon'),
    logoutButton: document.querySelector('.js-logout-button'),
    myCabinetButton: document.querySelector('.js-my-cabinet__button'),
    addCalls: document.querySelector('.js-search-container__button'),
    headerContainer: document.querySelector('.js-header-container'),
    myCabinetSection: document.querySelector('.js-calls-favourites'),
    pagginationSection: document.querySelector('.section-pagination'),
    cardSection: document.querySelector('.card'),
    pagButtons: document.querySelector('.section-btn'),
    clearButton: document.querySelector('.header-nav__clear__button'),
    listAuthButton: document.querySelector('.js-header-list__auth'),
    navMyCabinetButton: document.querySelector('.js-header-list__myCabinet'),
    navLogoutButton: document.querySelector('.js-nav-logout-button'),
    navContainer: document.querySelector('.js-header-nav__container'),
    mobileAddButton: document.querySelector('.header-add_button'),    
    seacrhSection: document.querySelector('.search-section'),
    // callsItem: document.querySelectorAll('.js-myCalls__item'),
    // favouritesItem: document.querySelectorAll('.js-favourites__list'),
}
